Reformat tiles
pranavs2001/Insta-Chef pull request #10
Opened 2021-03-01 00:29 UTC by pranavs2001

2021-03-01 22:22 UTC, jonathanbcarlson commented on src/tile.js
>    if (response.status >= 200 && response.status <= 299) {
is there a reason why you decided to move CheckError into src/tile.js? As opposed to importing it

2021-03-01 22:27 UTC, pranavs2001 commented
I updated the branch and removed the CheckError function from tile.js.

2021-03-01 23:22 UTC, jonathanbcarlson commented
> I updated the branch and removed the CheckError function from tile.js.

you got rid of CheckError but you didn't import it from src/Components/MealDB/ingredientsearch.js 
So there's no CheckError in src/tile.js. Did it work with `npm start`?

2021-03-02 05:33 UTC, jonathanbcarlson commented on src/Components/MealDB/recipewindow.js
> +        <p class="steps">{props.recipe.instructions}</p>
should you use className instead of class?

2021-03-02 05:33 UTC, jonathanbcarlson commented on src/Components/MealDB/recipewindow.js
> +        <button className="button-style" onClick={props.closeModal}>← Close</button>
does this need to be className="styles.button-style"?

2021-03-02 05:33 UTC, jonathanbcarlson commented on src/tile.js
>    }
seems unnecessary to have since it's never called

2021-03-02 05:33 UTC, jonathanbcarlson commented on src/tile.js
> +  // }
seems unnecessary to keep since it's never called

2021-03-02 05:33 UTC, jonathanbcarlson commented on src/tile.js
> +    //const flip = this.state.flipped;
also never used so can probably delete

2021-03-02 06:12 UTC, jonathanbcarlson requested changes

2021-03-02 06:12 UTC, jonathanbcarlson commented on src/tile.js
> +import styles from './tile.css';
styles isn't defined so maybe just import './tiles.css' similar to recipeWindow.css?

2021-03-02 06:12 UTC, jonathanbcarlson commented on src/tile.js
> +import styles from './tile.css';
also if you could removed flipped from Tile's state since it's not being used

2021-03-02 06:12 UTC, jonathanbcarlson commented on src/tile.js
> +        <button className="styles.tile_back" onClick={this.openRecipe}>
tile_back isn't defined in tile.css did you mean tile_front? also probably remove styles because of above import styles review comment

2021-03-02 06:23 UTC, jonathanbcarlson approved these changes

2021-03-02 06:39 UTC, merged